version: "3.9"

services:
    bot:
        build: .
        container_name: dodobot
        depends_on:
            - db
        env_file:
            - .env

    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 7777
            POSTGRES_DB: dodobot
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
